openapi: 3.1.0
info:
  title: Siege APIs
  version: 2025.11.10
  description: |-
    These are the Siege APIs I found by inspecting network requests. This is
    NOT an official documentation. Subject to change at any time.
servers:
  - url: https://siege.hackclub.com
tags:
  - name: public
    description: Public API
  - name: armory
    description: Project-related endpoints
security:
  - cookie: []

paths:
  /api/public-beta/projects:
    get:
      security: []
      tags: [public]
      description: Retrieve all projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIProject'
  /armory:
    post:
      tags: [armory]
      description: Create a new project
      requestBody:
        description: Project to create
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '302':
          description: Redirect to project page
          headers:
            Location:
              schema:
                type: string
                format: uri
  /armory/{id}:
    delete:
      tags: [armory]
      description: Delete a project
      parameters:
        - name: id
          in: path
          required: true
          description: ID of project to delete
          schema:
            type: integer
        - name: x-csrf-token
          in: header
          required: true
          description: CSRF token
          schema:
            type: string
      responses:
        '204':
          description: OK
    put:
      tags: [armory]
      description: Update a project
      parameters:
        - name: id
          in: path
          required: true
          description: ID of project to delete
          schema:
            type: integer
        - name: x-csrf-token
          in: header
          required: true
          description: CSRF token
          schema:
            type: string
      requestBody:
        description: Edited project
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EditProjectRequest'
  /armory/{id}/submit:
    post:
      tags: [armory]
      description: Submit a project
      parameters:
        - name: id
          in: path
          required: true
          description: ID of project to submit
          schema:
            type: integer
        - name: x-csrf-token
          in: header
          required: true
          description: CSRF token
          schema:
            type: string
      requestBody:
        description: Update status
        content:
          application/json:
            schema:
              type: object
              properties:
                is_update:
                  type: boolean
              required:
                - is_update
      responses:
        '200':
          description: OK

components:
  schemas:
    APIProject:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - building
            - submitted
            - pending_voting
            - waiting_for_review
            - finished
        repo_url:
          type: string
        demo_url:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            display_name:
              type: string
          required: [id, name, display_name]
        week_badge_text:
          type: string
        coin_value:
          type: string
        is_update:
          type: boolean
        hours:
          type: number
      required:
        - id
        - name
        - description
        - status
        - repo_url
        - demo_url
        - created_at
        - updated_at
        - user
        - week_badge_text
        - coin_value
        - is_update
        - hours
    CreateProjectRequest:
      allOf:
        - $ref: '#/components/schemas/AuthenticityToken'
        - type: object
          properties:
            remove_screenshot:
              type: boolean
            'project[name]':
              type: string
            'project[description]':
              type: string
            'project[repo_url]':
              type: string
            'project[demo_url]':
              type: string
            'project[screenshot]':
              type: string
              format: binary
            'project[hackatime_projects][]':
              type: array
              items:
                type: string
          required:
            - remove_screenshot
            - 'project[name]'
            - 'project[description]'
            - 'project[repo_url]'
            - 'project[demo_url]'
            - 'project[hackatime_projects][]'
    EditProjectRequest:
      allOf:
        - $ref: '#/components/schemas/AuthenticityToken'
        - type: object
          properties:
            _method:
              type: string
              enum:
                - patch
            remove_screenshot:
              type: boolean
            'project[name]':
              type: string
            'project[description]':
              type: string
            'project[repo_url]':
              type: string
            'project[demo_url]':
              type: string
            'project[screenshot]':
              type: string
              format: binary
            'project[hackatime_projects][]':
              type: array
              items:
                type: string
          required:
            - _method
            - remove_screenshot
            - 'project[name]'
            - 'project[description]'
            - 'project[repo_url]'
            - 'project[demo_url]'
            - 'project[hackatime_projects][]'
    AuthenticityToken:
      type: object
      properties:
        authenticity_token:
          type: string
      required:
        - authenticity_token
  securitySchemes:
    cookie:
      type: apiKey
      name: _siege_session
      in: cookie
